FROM adoptopenjdk:11-jre-hotspot
#dfg

#fdffn g

COPY target/kaddem-0.0.1-SNAPSHOT.jar.original kaddem-0.0.1-SNAPSHOT.jar.original
ENTRYPOINT ["java", "-jar", "kaddem-0.0.1-SNAPSHOT.jar.original"]
EXPOSE 9001