version: "3"

services:
  #springapp:
    #container_name: springbootapp
    #build: 'C:\Users\IHEB\Desktop\kaddem\ProjetDevops'
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kaddem
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app-kaddem:
    depends_on:
      - mysqldb
    image: "ihebbenothmen/projet-devops:latest"
    container_name: app-kaddem
    restart: on-failure
    ports:
      - 9001:9001
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/kaddemm?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true

volumes:
  db:
